USE `robogames`;

ALTER TABLE `RG_HABILITATION` 
CHANGE COLUMN `HAB_INFOS` `HAB_INFOS` VARCHAR(255) NULL ;

ALTER TABLE `RG_EVENEMENT` 
ADD COLUMN `EVE_NOM` VARCHAR(100) NOT NULL,
ADD UNIQUE INDEX `EVE_NOM_UNIQUE` (`EVE_NOM` ASC);

ALTER TABLE `RG_DEBRIEFING` 
CHANGE COLUMN `DEB_DEBRIEF` `DEB_DEBRIEF` LONGTEXT NULL ;


