USE `robogames`;

DROP TABLE RG_INFORMATIONS;

ALTER TABLE RG_USER
		ADD USER_NOM varchar(100) not null,
		ADD USER_PRENOM varchar(100) not null,
		ADD USER_PSEUDO varchar(100) not null,
		ADD USER_PASSWORD varchar(100) not null,
		ADD USER_EMAIL varchar(100) not null,
		ADD USER_ETAT boolean not null;
		
		
ALTER TABLE RG_USER
	ADD UNIQUE INDEX USER_PSEUDO_UNIQUE (USER_PSEUDO ASC);
	
ALTER TABLE RG_USER	
	ADD UNIQUE INDEX USER_EMAIL_UNIQUE (USER_EMAIL ASC);	