ALTER TABLE `robogames`.`rg_habilitation` 
CHANGE COLUMN `HAB_INFOS` `HAB_INFOS` VARCHAR(255) NULL ;

ALTER TABLE `robogames`.`rg_evenement` 
ADD COLUMN `EVE_NOM` VARCHAR(100) NOT NULL,
ADD UNIQUE INDEX `EVE_NOM_UNIQUE` (`EVE_NOM` ASC);

ALTER TABLE `robogames`.`rg_debriefing` 
CHANGE COLUMN `DEB_DEBRIEF` `DEB_DEBRIEF` LONGTEXT NULL ;
