USE `robogames`;

ALTER TABLE `RG_HABILITATION` 
ADD COLUMN `HAB_BAN_TIME` INT(11) NULL;

ALTER TABLE `RG_INFORMATIONS` 
CHANGE COLUMN `INF_NOM` `INF_NOM` VARCHAR(100) NULL ,
CHANGE COLUMN `INF_PRENOM` `INF_PRENOM` VARCHAR(100) NULL ;
